### ISSUE TITLE
Fallos en el tema dark

### ISSUE THREAD

**Issue by Madh93** [exo-do/nodebb-theme-exodus#2]
Actualmente en el foro hay algunos problemas con los estilos utilizando el tema oscuro. ¿Ya está solucionado?¿qué tema utiliza actualmente el foro?

![](http://imgur.com/iK6fBqol.png)

Saludos.

**Comment by exomarty** [comment]
Este no. El que usa el foro ya no se desarrolla por ser intercambiado por este en un futuro.

**Comment by exomarty** [comment]
Ya tenemos tema dark en el nuevo personalizador. Cierro aqui.
