### ISSUE TITLE
Salto de linea no se produce correctamente

### ISSUE THREAD

**Issue by alejandrocobo** [exo-do/nodebb-theme-exodus#3]
Buenas. Recientemente he migrado mi comunidad a NodeBB y he decidido usar vuestro tema. He visto que el salto de linea no se produce correctamente ya que corta la palabra por cualquier sitio. Os pongo una imagen de muestra. 
![combinacion2](https://cloud.githubusercontent.com/assets/1640709/19127028/93834174-8b3d-11e6-8bad-da76cb293f59.png)

Esto sucede tanto en la versión de escritorio como en la móvil. ¿Hay alguna forma de solucionarlo?

Gracias.

**Comment by exomarty** [comment]
tienes un enlace para verlo?
que version tienes instalada?

**Comment by alejandrocobo** [comment]
Se produce en cualquier topic. Por ejemplo se puede ver en este: https://foro.hardlimit.com/topic/61376/montando-una-vieja-gloria-k6-2-en-caja-at

Tengo la 1.2.0.

**Comment by exomarty** [comment]
tiene puesta esta directiva en algun css propio que es lo que te rompe el diseño
.content p {
    word-break: break-all;
}

el theme funciona bien puedes comprobarlo en https://exo.do aunque aun no se ha actualizado para la 1.2.0 aunque por lo visto no da grandes problemas

**Comment by segura2010** [comment]
como dice @exomarty el problema esta en el estilo que añadís a la etiqueta "p" para que rompa las palabras.

![](http://i.imgur.com/ejHeeeV.png)

**Comment by alejandrocobo** [comment]
Efectivamente, ese era el problema. Muchas gracias y felicidades por el trabajo que habéis hecho seguís haciendo.
